#sdks:
#  sdk1:
#    base_url: "https://test-cdn-global.configcat.com"
#    key: "XxPbCKmzIUGORk4vsufpzw/iC_KABprDEueeQs3yovVnQ"
#    poll_interval: 300
#    webhook_signing_key: "configcat_whsk_Dj59sEWxRmm+84izQ8Cbn9o4Pnjz7E+/hxcmyfEVT+A="
auto_config:
  key: 08ddb042-83a4-4a78-8465-4a6a6999cc78
  secret: dauf3zGIi8tV2c8wvxq7M1c1TcwPdgSGbm1y/+ndKfQ=
  base_url: "http://localhost:5200"
  poll_interval: 30
  log:
    level: "debug"

log:
  level: "error"

grpc:
  enabled: true
  log:
    level: "debug"
  port: 50052

diag:
  enabled: true
  port: 8091

http:
  port: 8090

tls:
  enabled: true
  certificates:
    - cert: "./internal/resources/cert/localhost.crt"
      key: "./internal/resources/cert/localhost.key"