#sdks:
#  sdk1:
#    base_url: "https://test-cdn-global.configcat.com"
#    key: "XxPbCKmzIUGORk4vsufpzw/iC_KABprDEueeQs3yovVnQ"
#    poll_interval: 300
#    webhook_signing_key: "configcat_whsk_Dj59sEWxRmm+84izQ8Cbn9o4Pnjz7E+/hxcmyfEVT+A="
#




profile:
  key: 08ddd139-5e60-4287-8894-047832f313b6
  secret: configcat_pst_3ZMdNsDQoDLgDc+UcgZP4CzxcWffKhj5jWSCljMVjS4=
  base_url: "https://test-api.configcat.com"
  poll_interval: 30
  sdks:
    base_url: "https://test-cdn-global.configcat.com"
  log:
    level: "debug"

#offline:
#  enabled: true

cache:
  redis:
    enabled: true
    addresses: ["127.0.0.1:6379"]

log:
  level: "error"

grpc:
  enabled: true
  log:
    level: "debug"
  port: 50052

diag:
  enabled: true
  port: 8091

http:
  port: 8090

tls:
  enabled: true
  certificates:
    - cert: "./internal/resources/cert/localhost.crt"
      key: "./internal/resources/cert/localhost.key"