sdks:
  sdk1:
    base_url: "https://test-cdn-global.configcat.com"
    key: "XxPbCKmzIUGORk4vsufpzw/iC_KABprDEueeQs3yovVnQ"
    poll_interval: 300
    webhook_signing_key: "configcat_whsk_Dj59sEWxRmm+84izQ8Cbn9o4Pnjz7E+/hxcmyfEVT+A="

log:
  level: "debug"

grpc:
  enabled: false
  port: 50052

http:
  port: 8090