#sdks:
#  sdk1:
#    base_url: "https://test-cdn-global.configcat.com"
#    key: "XxPbCKmzIUGORk4vsufpzw/iC_KABprDEueeQs3yovVnQ"
#    poll_interval: 300
#    webhook_signing_key: "configcat_whsk_Dj59sEWxRmm+84izQ8Cbn9o4Pnjz7E+/hxcmyfEVT+A="
auto_config:
  key: 08dd1f67-c86a-4de9-85d7-95040109ae6e
  secret: trjy4kurNnbvbU18eqxgBE73ji9IHcst09TKW/ErB/g=
  base_url: "http://localhost:5200"
  poll_interval: 30
  log:
    level: "debug"

log:
  level: "error"

grpc:
  enabled: true
  log:
    level: "debug"
  port: 50052

diag:
  enabled: true
  port: 8091

http:
  port: 8090

tls:
  enabled: true
  certificates:
    - cert: "./internal/resources/cert/localhost.crt"
      key: "./internal/resources/cert/localhost.key"