sdk:
  base_url: "https://test-cdn-global.configcat.com"
  key: "XxPbCKmzIUGORk4vsufpzw/iC_KABprDEueeQs3yovVnQ"
  poll_interval: 300
  log:
    level: "error"
  offline:
    enabled: true
    use_cache: false
    local:
      file_path: "./internal/resources/local.json"
      polling: true
  cache:
    redis:
      enabled: false

log:
  level: "debug"

grpc:
  enabled: false
  port: 50052

http:
  port: 8090
  webhook:
    enabled: true
    signing_key: "configcat_whsk_Dj59sEWxRmm+84izQ8Cbn9o4Pnjz7E+/hxcmyfEVT+A="
  cdn_proxy:
    enabled: true
  api:
    enabled: true

tls:
  enabled: true
  min_version: 1.3
  certificates:
    - cert: "./internal/resources/cert/localhost.crt"
      key: "./internal/resources/cert/localhost.key"

metrics:
  enabled: true
  port: 8091