sdks:
  sdk1:
    base_url: "https://test-cdn-global.configcat.com"
    key: "XxPbCKmzIUGORk4vsufpzw/iC_KABprDEueeQs3yovVnQ"
    poll_interval: 300
    webhook_signing_key: "configcat_whsk_Dj59sEWxRmm+84izQ8Cbn9o4Pnjz7E+/hxcmyfEVT+A="

log:
  level: "error"

grpc:
  enabled: true
  log:
    level: "debug"
  port: 50052

diag:
  enabled: true

http:
  port: 8090

tls:
  enabled: true
  certificates:
    - cert: "./internal/resources/cert/localhost.crt"
      key: "./internal/resources/cert/localhost.key"