#sdks:
#  sdk1:
#    base_url: "https://test-cdn-global.configcat.com"
#    key: "XxPbCKmzIUGORk4vsufpzw/iC_KABprDEueeQs3yovVnQ"
#    poll_interval: 300
#    webhook_signing_key: "configcat_whsk_Dj59sEWxRmm+84izQ8Cbn9o4Pnjz7E+/hxcmyfEVT+A="
#




auto_config:
  key: 08ddb657-51e9-4b6a-848e-017939e290fe
  secret: WxiC5C5Fb5lvI4K1ce7N5RDD6YRBVPDOo0n3mCddsdk=
  base_url: "https://test-api.configcat.com"
  sdk_base_url: "https://test-cdn-global.configcat.com"
  poll_interval: 30
  log:
    level: "debug"

log:
  level: "error"

grpc:
  enabled: true
  log:
    level: "debug"
  port: 50052

diag:
  enabled: true
  port: 8091

http:
  port: 8090

tls:
  enabled: true
  certificates:
    - cert: "./internal/resources/cert/localhost.crt"
      key: "./internal/resources/cert/localhost.key"