sdks:
  sdk1:
    base_url: "https://test-cdn-global.configcat.com"
    key: "XxPbCKmzIUGORk4vsufpzw/iC_KABprDEueeQs3yovVnQ"
    poll_interval: 300
    webhook_signing_key: "configcat_whsk_Dj59sEWxRmm+84izQ8Cbn9o4Pnjz7E+/hxcmyfEVT+A="
    log:
      level: "error"
    offline:
      enabled: true
      use_cache: false
      local:
        file_path: "./internal/resources/local.json"
        polling: false

cache:
  redis:
    enabled: false

eval_stats:
  influx_db:
    enabled: true
    url: http://localhost:8086
    organization: configcat
    bucket: flag_eval_stats
    auth_token: cD1ZfZr7-fHBGMd0Zcb2DaJBCqiD9Y47-HI8yK343BsvN0Og6TXU7-bCmL0kxD77JqR7OkjViYBOt1zhFD5D1w==

log:
  level: "debug"

grpc:
  enabled: false
  port: 50052

http:
  port: 8090
  webhook:
    enabled: true
  cdn_proxy:
    enabled: true
  api:
    enabled: true

#http_proxy:
#  url: http://localhost:3128

tls:
  enabled: true
  min_version: 1.3
  certificates:
    - cert: "./internal/resources/cert/localhost.crt"
      key: "./internal/resources/cert/localhost.key"

metrics:
  enabled: true
  port: 8091