version: 2

project_name: configcat-proxy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/configcat/configcat-proxy/sdk.proxyVersion={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    goarm:
      - '7'

archives:
  - format: tar.gz
    format_overrides:
    - goos: windows
      format: zip

dockers:
  - image_templates:
    - "configcat/proxy:{{.Version}}-amd64"
    - "configcat/proxy:v{{.Major}}-amd64"
    - "configcat/proxy:{{.Major}}.{{.Minor}}-amd64"
    - "configcat/proxy:latest-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  
  - image_templates:
    - "configcat/proxy:{{.Version}}-arm64"
    - "configcat/proxy:v{{.Major}}-arm64"
    - "configcat/proxy:{{.Major}}.{{.Minor}}-arm64"
    - "configcat/proxy:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "configcat/proxy:{{.Version}}"
    image_templates:
    - "configcat/proxy:{{.Version}}-amd64"
    - "configcat/proxy:{{.Version}}-arm64"
  
  - name_template: "configcat/proxy:v{{.Major}}"
    image_templates:
    - "configcat/proxy:v{{.Major}}-amd64"
    - "configcat/proxy:v{{.Major}}-arm64"

  - name_template: "configcat/proxy:{{.Major}}.{{.Minor}}"
    image_templates:
    - "configcat/proxy:{{.Major}}.{{.Minor}}-amd64"
    - "configcat/proxy:{{.Major}}.{{.Minor}}-arm64"

  - name_template: "configcat/proxy:latest"
    image_templates:
    - "configcat/proxy:latest-amd64"
    - "configcat/proxy:latest-arm64"

