version: "3.4"

volumes:
  prometheus:
  grafana:
  redis_insight:

configs:
  prometheus_3:
    file: resources/monitor/prometheus.yml
  grafana_datasource_2:
    file: resources/monitor/grafana_ds.yml
  grafana_dashboards_1:
    file: resources/monitor/dashboards.yml
  grafana_dashboard_1:
    file: resources/monitor/proxy_dashboard.json

services:
  configcat_proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - CONFIGCAT_SDK_BASE_URL=https://test-cdn-global.configcat.com
      - CONFIGCAT_SDK_KEY=XxPbCKmzIUGORk4vsufpzw/iC_KABprDEueeQs3yovVnQ
      - CONFIGCAT_SDK_POLL_INTERVAL=300
      - CONFIGCAT_HTTP_WEBHOOK_SIGNING_KEY=configcat_whsk_Dj59sEWxRmm+84izQ8Cbn9o4Pnjz7E+/hxcmyfEVT+A=
      - CONFIGCAT_SDK_CACHE_REDIS_ENABLED=true
      - CONFIGCAT_SDK_CACHE_REDIS_ADDRESSES=["redis:6379"]
    ports:
      - "8050:8050"
      - "8051:8051"
      - "50051:50051"

  prometheus:
    image: prom/prometheus
    configs:
      - source: prometheus_3
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    configs:
      - source: grafana_datasource_2
        target: /etc/grafana/provisioning/datasources/prometheus.yml
      - source: grafana_dashboards_1
        target: /etc/grafana/provisioning/dashboards/dashboards.yml
      - source: grafana_dashboard_1
        target: /etc/grafana/provisioning/dashboards/proxy/proxy_dashboard.json

  redis:
    image: redis:7.0.8-alpine3.17
    ports:
      - "6379:6379"