version: "3.4"

volumes:
  prometheus:
  grafana:
  influxdb:

configs:
  prometheus_4:
    file: internal/resources/monitor/prometheus.yml
  grafana_datasource_3:
    file: internal/resources/monitor/grafana_ds.yml
  grafana_dashboards_2:
    file: internal/resources/monitor/dashboards.yml
  grafana_dashboard_9:
    file: internal/resources/monitor/proxy_dashboard.json

services:
  configcat_proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./internal/resources/cert:/cert
    environment:
      - CONFIGCAT_SDKS={"sdk1":"XxPbCKmzIUGORk4vsufpzw/iC_KABprDEueeQs3yovVnQ", "sdk2":"XxPbCKmzIUGORk4vsufpzw/6ft7XQudcEuIXY49grZM9w"}
      - CONFIGCAT_SDK1_BASE_URL=https://test-cdn-global.configcat.com
      - CONFIGCAT_SDK1_POLL_INTERVAL=300
      - CONFIGCAT_SDK1_LOG_LEVEL=error
      - CONFIGCAT_SDK1_WEBHOOK_SIGNING_KEY=configcat_whsk_Dj59sEWxRmm+84izQ8Cbn9o4Pnjz7E+/hxcmyfEVT+A=
      - CONFIGCAT_SDK2_BASE_URL=https://test-cdn-global.configcat.com
      - CONFIGCAT_SDK2_POLL_INTERVAL=300
      - CONFIGCAT_SDK2_WEBHOOK_SIGNING_KEY=configcat_whsk_a8w2b38Ofhs0rzXbZhNCvPTeTeUxmerTBy9PzMCX6+E=
#      - CONFIGCAT_SDK2_OFFLINE_ENABLED=true
#      - CONFIGCAT_SDK2_OFFLINE_USE_CACHE=true
      - CONFIGCAT_SDK2_LOG_LEVEL=error
      - CONFIGCAT_CACHE_REDIS_ENABLED=true
      - CONFIGCAT_CACHE_REDIS_ADDRESSES=["redis:6379"]
      - CONFIGCAT_TLS_ENABLED=true
      - CONFIGCAT_TLS_CERTIFICATES=[{"key":"./cert/localhost.key","cert":"./cert/localhost.crt"}]
      - CONFIGCAT_HTTP_PROXY_URL=http://squid:3128
      - CONFIGCAT_EVAL_STATS_INFLUX_DB_ENABLED=true
      - CONFIGCAT_EVAL_STATS_INFLUX_DB_URL=http://influxdb:8086
      - CONFIGCAT_EVAL_STATS_INFLUX_DB_ORGANIZATION=configcat
      - CONFIGCAT_EVAL_STATS_INFLUX_DB_BUCKET=flag_eval_stats
      - CONFIGCAT_EVAL_STATS_INFLUX_DB_AUTH_TOKEN=cD1ZfZr7-fHBGMd0Zcb2DaJBCqiD9Y47-HI8yK343BsvN0Og6TXU7-bCmL0kxD77JqR7OkjViYBOt1zhFD5D1w==
    ports:
      - "8050:8050"
      - "8051:8051"
      - "50051:50051"

  prometheus:
    image: prom/prometheus
    configs:
      - source: prometheus_4
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3100:3000"
    volumes:
      - grafana:/var/lib/grafana
    configs:
      - source: grafana_datasource_3
        target: /etc/grafana/provisioning/datasources/prometheus.yml
      - source: grafana_dashboards_2
        target: /etc/grafana/provisioning/dashboards/dashboards.yml
      - source: grafana_dashboard_9
        target: /etc/grafana/provisioning/dashboards/proxy/proxy_dashboard.json

  redis:
    image: redis:7.0.8-alpine3.17
    ports:
      - "6379:6379"

  squid:
    image: ubuntu/squid
    ports:
      - "3128:3128"

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234
      - DOCKER_INFLUXDB_INIT_ORG=configcat
      - DOCKER_INFLUXDB_INIT_BUCKET=flag_eval_stats