global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: configcat_proxy
    metrics_path: /metrics
    static_configs:
      - targets:
          - configcat_proxy:8051