{
 "title": "Proxy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"configcat_proxy:8051\"}[$__rate_interval]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "go_threads{instance=\"configcat_proxy:8051\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"configcat_proxy:8051\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSE Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "configcat_stream_connections{type=\"sse\", instance=\"configcat_proxy:8051\"} > 0",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "GRPC Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "configcat_stream_connections{type=\"grpc\", instance=\"configcat_proxy:8051\"} > 0",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"configcat_proxy:8051\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(configcat_http_request_duration_seconds_count{instance=\"configcat_proxy:8051\"}[$__rate_interval])) by (route, method, status) > 0",
     "legendFormat": "{{route}} - {{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, route) (rate(configcat_http_request_duration_seconds_bucket{instance=\"configcat_proxy:8051\"}[$__rate_interval]))) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SDK Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(configcat_sdk_http_request_duration_seconds_count{instance=\"configcat_proxy:8051\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "SDK Response Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, route) (rate(configcat_sdk_http_request_duration_seconds_bucket{instance=\"configcat_proxy:8051\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory allocation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"configcat_proxy:8051\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pause",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(go_gc_duration_seconds_sum{instance=\"configcat_proxy:8051\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=\"configcat_proxy:8051\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}