name: Proxy Release

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
    
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.x
          
    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test ./...

    - name: Test with race
      run: go test -race ./...

  release-docker:
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
      - uses: actions/checkout@v3

      - name: Download executables
        uses: actions/download-artifact@v3
        with:
          name: executables

      - name: Get version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
              configcat/proxy:latest
              configcat/proxy:${{ env.VERSION }}

  release-goreleaser:
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}