name: Proxy Release

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
    
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongodb/mongodb-community-server
        ports:
          - 27017:27017
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
          
    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test ./...

    - name: Test with race
      run: go test -race ./...

  release-goreleaser:
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}